<?php
/**
 * @var $block \Cap\Brand\Block\Adminhtml\Category\LinkProducts
 */

$collection = $block->getProductCollection();
$attributeCode = $block->getConfigBrandAttributeCode();

?>
<table class="data-grid data-grid-draggable">
    <thead>
    <tr>
        <th scope="col">Name</th>
        <th scope="col">Attribute Code</th>
        <th scope="col">Matching Brand Id</th>
        <th scope="col">Visibility</th>
        <th scope="col">Current Categories Id</th>
        <th scope="col">Brand Category Id to merge</th>
        <th scope="col">Final Categories</th>
    </tr>
    </thead>
    <tbody>
    <?php /** @var $product \Magento\Catalog\Model\Product */ ?>
    <?php foreach ($collection as $product): ?>
        <?php $brand = $block->getProductBrand($product); ?>
        <?php $productCategories = $product->getCategoryIds(); ?>
        <tr>
            <td><?= $product->getName() ?></td>
            <td><?= $product->getData($attributeCode) ?></td>
            <td>
                <?php if ($brand): ?>
                    <?= $brand->getBrandId() ?>
                <?php endif; ?>
            </td>
            <td><?= $product->getAttributeText('visibility'); ?></td>
            <td><?php print_r($productCategories) ?></td>
            <td>
                <?php if ($brand): ?>
                    <?php if (in_array($brand->getCategoryId(), $productCategories)): ?>
                        <?= 'Already merged' ?>
                    <?php else: ?>
                        <?= $brand->getCategoryId() ?>
                    <?php endif; ?>
                <?php endif; ?>
            </td>
            <td>
                <?php if ($brand): ?>
                    <?php if (!in_array($brand->getCategoryId(), $productCategories)): ?>
                        <?php $productCategories = array_merge($productCategories, [$brand->getCategoryId()]) ?>
                        <?php print_r($productCategories) ?>
                    <?php endif; ?>
                <?php endif; ?>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>
