<?php
/**
 * Brands List Widget template file.
 *
 * @var \Cap\Brand\Block\Widget\Brands $block
 * @var $escaper \Magento\Framework\Escaper
 */

$collection = $block->getBrands();
$array = $block->getBrandsGroupedByCharacter();

//todo: template
?>
<?php if ($collection->count()): ?>
    <div class="widget-brands-list">
        <?php foreach ($array as $key => $letter): ?>
            <h3><?= $escaper->escapeHtml($key); ?></h3>
            <ul>
                <?php foreach ($letter as $item): ?>
                    <li>
                        <?php if ($block->getData('show_brand_small_image')): ?>
                            <a href="<?= $escaper->escapeUrl($item['url']); ?>" title="<?= $escaper->escapeHtml($item['title']); ?>">
                                <img src="<?= $escaper->escapeUrl($item['small_image']); ?>" alt="<?= $escaper->escapeHtml($item['title']); ?>">
                            </a>
                        <?php endif; ?>
                        <?php if ($block->getData('show_brand_name')): ?>
                            <a href="<?= $escaper->escapeUrl($item['url']); ?>" title="<?= $escaper->escapeHtml($item['title']); ?>"><?= $escaper->escapeHtml($item['title']); ?></a>
                        <?php endif; ?>
                    </li>
                <?php endforeach; ?>
            </ul>
        <?php endforeach; ?>
    </div>
<?php endif; ?>
