<?php
/**
 * Brands List Widget template file.
 *
 * @var \Cap\Brand\Block\Widget\Brands $block
 * @var $escaper \Magento\Framework\Escaper
 */

$collection = $block->getBrands();
?>

<?php foreach ($collection as $brand): ?>
    <?php if ($block->getData('show_brand_name')): ?>
        <?= $escaper->escapeHtml($brand->getTitle()) ?>
    <?php endif; ?>
    <a class="brand" title="<?= $escaper->escapeHtml($brand->getTitle()) ?>"
       href="<?= $escaper->escapeUrl($block->getBrandUrl($brand)) ?>">
        <img src="<?= $escaper->escapeUrl($block->getBrandSmallImageUrl($brand)) ?>"
             alt="<?= $escaper->escapeHtml($brand->getTitle()) . ' ' . __('logo') ?>""/>
    </a>
<?php endforeach; ?>
