<?php
/**
 * @var $block \Magento\Catalog\Block\Product\View
 * @var $viewModel \Cap\Brand\ViewModel\Product\View
 * @var $escaper \Magento\Framework\Escaper
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */

$viewModel = $block->getViewModel();
?>

<?php if ($exist = $viewModel->getProductRelatedBrandCollection($block->getProduct())->getSize()): ?>
<?php
$type = $block->getType();
$class = $type;
$image = 'related_products_list';
$title = __('Same Brand Products');
$items = $viewModel->getProductRelatedBrandCollection($block->getProduct());
$limit = $viewModel->getConfigRelatedProductPerRow();
$shuffle = 0;
$isWeightedRandom = 0;
$showAddTo = false;
?>
<div class="block <?= $escaper->escapeHtmlAttr($class) ?>"
     data-mage-init='{"relatedProducts":{"relatedCheckbox":".related.checkbox"}}'
     data-limit="<?= $escaper->escapeHtmlAttr($limit) ?>"
     data-shuffle="<?= /* @noEscape */ $shuffle ?>"
     data-shuffle-weighted="<?= /* @noEscape */ $isWeightedRandom ?>">
    <div class="block-title title">
        <strong id="block-<?= $escaper->escapeHtmlAttr($class) ?>-heading" role="heading"
                aria-level="2"><?= $escaper->escapeHtml($title) ?></strong>
    </div>
    <div class="block-content content" aria-labelledby="block-<?= $escaper->escapeHtmlAttr($class) ?>-heading">
        <div class="products wrapper grid products-grid products-<?= $escaper->escapeHtmlAttr($type) ?>">
            <ol class="products list items product-items">
                <?php foreach ($items as $_item):?>
                    <li class="item product product-item"
                    id="product-item_<?= /* @noEscape */ $_item->getId() ?>"
                    data-shuffle-group="<?= $escaper->escapeHtmlAttr($_item->getPriority()) ?>" >
                    <?= /* @noEscape */ $secureRenderer->renderStyleAsTag(
                        'display:none;',
                        'li#product-item_' . $_item->getId()
                    ) ?>
                    <div class="product-item-info">
                        <?= /* @noEscape */ '<!-- ' . $image . '-->' ?>
                        <a href="<?= $escaper->escapeUrl($block->getProductUrl($_item)) ?>"
                           class="product photo product-item-photo">
                            <?= $block->getImage($_item, $image)->toHtml() ?>
                        </a>
                        <div class="product details product-item-details">
                            <strong class="product name product-item-name"><a
                                        class="product-item-link"
                                        title="<?= $escaper->escapeHtmlAttr($_item->getName()) ?>"
                                        href="<?= $escaper->escapeUrl($block->getProductUrl($_item)) ?>">
                                    <?= $escaper->escapeHtml($_item->getName()) ?></a>
                            </strong>

                            <?= /* @noEscape */ $block->getProductPrice($_item) ?>

                            <?php if ($showAddTo):?>
                                <?php // phpcs:disable ?>
                                <div class="product actions product-item-actions">
                                    <div class="secondary-addto-links actions-secondary"
                                         data-role="add-to-links">
                                        <?php if ($addToBlock = $block->getChildBlock('addto')):?>
                                            <?= $addToBlock->setProduct($_item)->getChildHtml() ?>
                                        <?php endif; ?>
                                    </div>
                                </div>
                                <?php // phpcs:enable ?>
                            <?php endif; ?>
                        </div>
                    </div>
                    </li>
                <?php endforeach ?>
            </ol>
        </div>
    </div>
</div>
<?php endif;?>
